#general
command_timeout = 500

[container]
disabled = true

[character]
success_symbol = "[❯](blue)"

[directory]
use_os_path_sep = false #when on windows

[username]
show_always = true
style_user = ""
style_root = ""
format = "[$user]($style)"

[hostname]
ssh_only = false
format =  "@$hostname "

[git_branch]
format = "[$symbol$branch]($style) "

[time]
disabled = false
style = "blue"
use_12hr = true
format = "[$time]($style) "

[cmd_duration]
min_time = 10_000
format = "[$duration]($style) "
